function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed")}}}
function t454_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t454__list_item a[href='"+url+"']").addClass("t-active");$(".t454__list_item a[href='"+url+"/']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t454_checkAnchorLinks(recid){if($(window).width()>=960){var t454_navLinks=$("#rec"+recid+" .t454__list_item a:not(.tooltipstered)[href*='#']");if(t454_navLinks.length>0){setTimeout(function(){t454_catchScroll(t454_navLinks)},500)}}}
function t454_catchScroll(t454_navLinks){var t454_clickedSectionId=null,t454_sections=new Array(),t454_sectionIdTonavigationLink=[],t454_interval=100,t454_lastCall,t454_timeoutId;t454_navLinks=$(t454_navLinks.get().reverse());t454_navLinks.each(function(){var t454_cursection=t454_getSectionByHref($(this));if(typeof t454_cursection.attr("id")!="undefined"){t454_sections.push(t454_cursection)}
t454_sectionIdTonavigationLink[t454_cursection.attr("id")]=$(this)});t454_updateSectionsOffsets(t454_sections);$(window).bind('resize',t_throttle(function(){t454_updateSectionsOffsets(t454_sections)},200));$('.t454').bind('displayChanged',function(){t454_updateSectionsOffsets(t454_sections)});setInterval(function(){t454_updateSectionsOffsets(t454_sections)},5000);t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId);t454_navLinks.click(function(){var clickedSection=t454_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof clickedSection.attr("id")!="undefined"){t454_navLinks.removeClass('t-active');$(this).addClass('t-active');t454_clickedSectionId=t454_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t454_now=new Date().getTime();if(t454_lastCall&&t454_now<(t454_lastCall+t454_interval)){clearTimeout(t454_timeoutId);t454_timeoutId=setTimeout(function(){t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)},t454_interval-(t454_now-t454_lastCall))}else{t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)}})}
function t454_updateSectionsOffsets(sections){$(sections).each(function(){var t454_curSection=$(this);t454_curSection.attr("data-offset-top",t454_curSection.offset().top)})}
function t454_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue+"']")}}
function t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId){var t454_scrollPosition=$(window).scrollTop(),t454_valueToReturn=t454_clickedSectionId;if(t454_sections.length!=0&&t454_clickedSectionId==null&&t454_sections[t454_sections.length-1].attr("data-offset-top")>(t454_scrollPosition+300)){t454_navLinks.removeClass('t-active');return null}
$(t454_sections).each(function(e){var t454_curSection=$(this),t454_sectionTop=t454_curSection.attr("data-offset-top"),t454_id=t454_curSection.attr('id'),t454_navLink=t454_sectionIdTonavigationLink[t454_id];if(((t454_scrollPosition+300)>=t454_sectionTop)||(t454_sections[0].attr("id")==t454_id&&t454_scrollPosition>=$(document).height()-$(window).height())){if(t454_clickedSectionId==null&&!t454_navLink.hasClass('t-active')){t454_navLinks.removeClass('t-active');t454_navLink.addClass('t-active');t454_valueToReturn=null}else{if(t454_clickedSectionId!=null&&t454_id==t454_clickedSectionId){t454_valueToReturn=null}}
return!1}});return t454_valueToReturn}
function t454_setPath(){}
function t454_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t454_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-80px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t454_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t454_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t454"),burger=el.find(".t454__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t454_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t454_setLogoPadding(recid){if($(window).width()>980){var t454__menu=$('#rec'+recid+' .t454');var t454__logo=t454__menu.find('.t454__logowrapper');var t454__leftpart=t454__menu.find('.t454__leftwrapper');var t454__rightpart=t454__menu.find('.t454__rightwrapper');t454__leftpart.css("padding-right",t454__logo.width()/2+50);t454__rightpart.css("padding-left",t454__logo.width()/2+50)}}
function t668_init(recid){var el=$('#rec'+recid);var toggler=el.find(".t668__header");var accordion=el.find('.t668__accordion');if(accordion){accordion=accordion.attr('data-accordion')}else{accordion="false"}
toggler.click(function(){if(accordion==="true"){toggler.not(this).removeClass("t668__opened").next().slideUp()}
$(this).toggleClass("t668__opened");$(this).next().slideToggle();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t734_init(recid){var rec=$('#rec'+recid);if($('body').find('.t830').length>0){if(rec.find('.t-slds__items-wrapper').hasClass('t-slds_animated-none')){t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})}else{setTimeout(function(){t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})},500)}}else{t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})}
rec.find('.t734').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}
function t786__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t786_initPopup(recid);t786__hoverZoom_init(recid);t786__updateLazyLoad(recid);t786__alignButtons_init(recid);if(typeof t_store_addProductQuantityEvents!=='undefined'){t786_initProductQuantity(recid)}},500)}
function t786_initProductQuantity(recid){var el=$('#rec'+recid);var productList=el.find(".t786__col, .t786__product-full");productList.each(function(i,product){t_store_addProductQuantityEvents($(product))})}
function t786__alignButtons_init(recid){var el=$('#rec'+recid);if(el.find('[data-buttons-v-align]')[0]){try{t786__alignButtons(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t786__alignButtons(recid)}));el.find('.t786').bind('displayChanged',function(){t786__alignButtons(recid)});if($isMobile){$(window).on('orientationchange',function(){t786__alignButtons(recid)})}}catch(e){console.log('buttons-v-align error: '+e.message)}}}
function t786__showMore(recid){var el=$('#rec'+recid).find(".t786");var showmore=el.find('.t786__showmore');var cards_count=parseInt(el.attr('data-show-count'),10);if(cards_count>0){if(showmore.text()===''){showmore.find('td').text(t786__dict('loadmore'))}
showmore.show();el.find('.t786__col').hide();var cards_size=el.find('.t786__col').size();var x=cards_count;var y=cards_count;t786__showSeparator(el,x);el.find('.t786__col:lt('+x+')').show();showmore.click(function(){x=(x+y<=cards_size)?x+y:cards_size;el.find('.t786__col:lt('+x+')').show();if(x==cards_size){showmore.hide()}
t786__showSeparator(el,x);if($('#rec'+recid).find('[data-buttons-v-align]')[0]){t786__alignButtons(recid)}
if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t786__dict(msg){var dict=[];dict.loadmore={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var lang=window.browserLang;if(typeof dict[msg]!=='undefined'){if(typeof dict[msg][lang]!=='undefined'&&dict[msg][lang]!=''){return dict[msg][lang]}else{return dict[msg].EN}}
return 'Text not found "'+msg+'"'}
function t786__showSeparator(el,x){el.find('.t786__separator_number').addClass('t786__separator_hide');el.find('.t786__separator_hide').each(function(){if($(this).attr('data-product-separator-number')<=x){$(this).removeClass('t786__separator_hide')}})}
function t786__alignButtons(recid){var rec=$('#rec'+recid);var wrappers=rec.find('.t786__textwrapper');var maxHeight=0;var itemsInRow=rec.find('.t-container').attr('data-blocks-per-row')*1;var mobileView=$(window).width()<=480;var tableView=$(window).width()<=960&&$(window).width()>480;var mobileOneRow=$(window).width()<=960&&rec.find('.t786__container_mobile-flex')[0]?!0:!1;var mobileTwoItemsInRow=$(window).width()<=480&&rec.find('.t786 .mobile-two-columns')[0]?!0:!1;if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var i=1;var wrappersInRow=[];$.each(wrappers,function(key,element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
$.each(wrappersInRow,function(key,wrapper){wrapper.style.height=maxHeight+'px'});if(i===itemsInRow){i=0;maxHeight=0;wrappersInRow=[]}
i++}})}
function t786__hoverZoom_init(recid){if(isMobile){return}
var rec=$('#rec'+recid);try{if(rec.find('[data-hover-zoom]')[0]){if(!jQuery.cachedZoomScript){jQuery.cachedZoomScript=function(url){var options={dataType:'script',cache:!0,url:url};return jQuery.ajax(options)}}
$.cachedZoomScript('https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js').done(function(script,textStatus){if(textStatus=='success'){setTimeout(function(){t_hoverZoom_init(recid,".t-slds__container")},500)}else{console.log('Upload script error: '+textStatus)}})}}catch(e){console.log('Zoom image init error: '+e.message)}}
function t786__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t786__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t786_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t786__product-'+lid_prod+'')})});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();t786_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]');el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t786_updateSlider(recid+' #t786__product-'+lid_prod+'');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});if($('#record'+recid).length==0){t786_checkUrl(recid)}
t786_copyTypography(recid)}
function t786_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/')}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t786_updateSlider(recid){var el=$('#rec'+recid);t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t786_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t786_closePopup()}});el.find('.t-popup__close, .t786__close-text').click(function(e){t786_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t786_closePopup()}})}
function t786_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/')}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t786_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t786_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t786__title').attr('style');var descrStyle=rec.find('.t786__descr').attr('style');rec.find('.t-popup .t786__title').attr("style",t786_removeSizeStyles(titleStyle));rec.find('.t-popup .t786__descr, .t-popup .t786__text').attr("style",t786_removeSizeStyles(descrStyle))}
function t796_init(recid){var el=$("#rec"+recid);var winWidth=$(window).width();var screenMin=el.attr("data-screen-min");var screenMax=el.attr("data-screen-max");if(typeof screenMin!=='undefined'){if(winWidth<parseInt(screenMin,10)){return!1}}
if(typeof screenMax!=='undefined'){if(winWidth>parseInt(screenMax,10)){return!1}}
var shapeEl=el.find(".t796__shape-border");var recs=el.find(".t796").attr("data-shape-rec-ids");if(typeof recs!="undefined"){recs=recs.split(",");recs.forEach(function(rec_id,i,arr){var curRec=$("#rec"+rec_id);var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)})}else{var excludesBlocks=[215,316,390,651,702,706,708,750,756,766,825,862,868,];var excludes='';excludesBlocks.forEach(function(el){excludes+='[data-record-type=\''+el+'\'],'});if(excludes.slice(-1)===','){excludes=excludes.slice(0,-1)}
var curRec;if(shapeEl.hasClass('t796__shape-border_top')||shapeEl.hasClass('t796__shape-border_top-flip')){curRec=el.nextAll(".r:not("+excludes+")").eq(0)}
if(shapeEl.hasClass('t796__shape-border_bottom')||shapeEl.hasClass('t796__shape-border_bottom-flip')){curRec=el.prevAll(".r:not("+excludes+")").eq(0)}
if(curRec.length!==0){var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)}}}
function t796_addDivider(curRec,curShapeEl){curRec.attr("data-animationappear","off").removeClass('r_hidden');var coverWrapper=curRec.find(".t-cover");var zeroWrapper=curRec.find(".t396");if(coverWrapper.find('.t557__snow-layer').length>0){curShapeEl.css('z-index',1)}
if(coverWrapper.length>0||zeroWrapper.length>0){if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(curShapeEl)}
if(zeroWrapper.length>0){zeroWrapper.after(curShapeEl);curRec.css("position","relative")}
if(zeroWrapper.find('.t396__filter').length>0){curShapeEl.css('z-index',1)}
curShapeEl.css("display","block")}else{var wrapper=curRec;var curRecType=Number.parseInt(curRec.attr("data-record-type"));if(wrapper.length===0){return!0}
wrapper.append(curShapeEl);wrapper.css("position","relative");var excludesBlocks=[125,331,554,746,754,776,778,786,858,896,897,924,915,951,];if(excludesBlocks.indexOf(curRecType)===-1){wrapper.children("div").first().css({"position":"relative","z-index":"1"}).addClass("t796_cont-near-shape-divider")}
var blocks=[195,279,675,694,734,938,];if(blocks.indexOf(curRecType)!==-1){curShapeEl.css("z-index",1)}
curShapeEl.css("display","block")}}
function t796_setColor(el,curShapeEl){if(typeof curShapeEl.attr("data-fill-color")!="undefined"){return}
var nearestBlock;if(curShapeEl.hasClass("t796__shape-border_bottom")||curShapeEl.hasClass("t796__shape-border_bottom-flip")){nearestBlock=el.next(".r")}else{nearestBlock=el.prev(".r")}
if(nearestBlock.length===0){return}
var fillColor=nearestBlock.attr("data-bg-color");if(typeof fillColor=="undefined"){return}
curShapeEl.find(".t796__svg").css("fill",fillColor)}